// Gallery — two horizontally-scrolling marquee rows of LOGO.AI-generated
// example logos, mirroring HEADSHOT's gallery pattern. Uses real logo
// images from /images/Logos so the section feels concrete.

import Image from 'next/image'

const ROW_A = [
  '/images/Logos/restaurant-logo-1.webp',
  '/images/Logos/coffee-shop-logo-1.webp',
  '/images/Logos/bakery-logo-1.webp',
  '/images/Logos/food-truck-logo-1.webp',
  '/images/Logos/barbershop-logo-1.webp',
  '/images/Logos/hair-salon-logo-1.webp',
  '/images/Logos/nail-studio-logo-1.webp',
  '/images/Logos/boutique-logo-1.webp',
]

const ROW_B = [
  '/images/Logos/clothing-brand-logo-1.webp',
  '/images/Logos/gym-logo-1.webp',
  '/images/Logos/cleaning-service-logo-1.webp',
  '/images/Logos/landscaping-company-logo-1.webp',
  '/images/Logos/pet-grooming-logo-1.webp',
  '/images/Logos/e-commerce-brand-logo-7.webp',
  '/images/Logos/content-creator-logo-1.webp',
  '/images/Logos/tattoo-studio-logo-1.webp',
]

function MarqueeRow({ tiles }: { tiles: string[] }) {
  // Duplicate inline so the track is exactly 2x — translating by -50% loops seamlessly.
  const doubled = [...tiles, ...tiles]
  return (
    <div className="m-marquee-row relative w-full overflow-hidden">
      <div className="m-marquee-track">
        {doubled.map((src, i) => (
          <div
            key={`${src}-${i}`}
            className="relative shrink-0 mx-2 overflow-hidden p-px"
            style={{
              width: 280,
              height: 280,
              borderRadius: '14px',
              border: '1px solid var(--m-border-soft)',
              background: 'var(--m-surface-alt)',
            }}
            aria-hidden={i >= tiles.length}
          >
            <div className="relative w-full h-full overflow-hidden" style={{ borderRadius: 13 }}>
              <Image
                src={src}
                alt=""
                fill
                sizes="280px"
                className="object-contain p-6"
              />
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

export default function MGallery() {
  return (
    <section
      id="gallery"
      className="flex flex-col items-start py-20 md:pb-[128px] md:pt-0 px-5 sm:px-10 md:px-16 lg:px-[96px] w-full"
      style={{ background: 'var(--m-surface)' }}
    >
      <div className="flex flex-col gap-8 items-start w-full max-w-[1728px] px-2 sm:px-4">
        {/* Heading block */}
        <div className="flex flex-col gap-4 items-start w-full">
          <p className="m-eyebrow-lg w-full">Examples</p>
          <h2 className="m-h2 w-full" style={{ color: 'var(--m-ink-deep)' }}>
            Original Logos, Designed Live
          </h2>
          <p className="m-sub w-full" style={{ fontSize: 20, lineHeight: '28px' }}>
            Every logo below was generated by LOGO.AI from a single brand description — in under sixty seconds. No human touch-ups. No templates. No stock assets.
          </p>
        </div>

        {/* Marquee — two rows */}
        <div
          className="relative w-full overflow-hidden flex flex-col gap-4 py-4"
          style={{ background: 'var(--m-surface)', borderRadius: 'var(--m-radius-lg)' }}
          aria-label="Scrolling gallery of AI-generated logos"
        >
          <MarqueeRow tiles={ROW_A} />
          <MarqueeRow tiles={ROW_B} />

          {/* Edge fades */}
          <div
            aria-hidden="true"
            className="pointer-events-none absolute top-0 bottom-0 left-0"
            style={{ width: 120, background: 'linear-gradient(to right, var(--m-surface), transparent)' }}
          />
          <div
            aria-hidden="true"
            className="pointer-events-none absolute top-0 bottom-0 right-0"
            style={{ width: 120, background: 'linear-gradient(to left, var(--m-surface), transparent)' }}
          />
        </div>
      </div>
    </section>
  )
}
