'use client'

import { useState } from 'react'
import Badge from './ui/Badge'
import CategoryTabs from './CategoryTabs'
import LogoGrid from './LogoGrid'
import { getCategoryImages } from '@/data'

export default function LogoGallerySection() {
  const [active, setActive] = useState('restaurant')
  const [animKey, setAnimKey] = useState(0)

  const handleSelect = (key: string) => {
    if (key === active) return
    setActive(key)
    setAnimKey((k) => k + 1)
  }

  return (
    <section
      className="px-5 md:px-8 lg:px-10 py-16 md:py-[120px]"
      style={{ borderTop: '1px solid rgba(84,87,94,0.3)', borderBottom: '1px solid rgba(84,87,94,0.3)' }}
    >
      <div className="max-w-[95%] sm:max-w-[90%] mx-auto flex flex-col gap-8 md:gap-[60px]">
        <div className="flex flex-col gap-2.5">
          <Badge icon="fingerprint" text="100% original" />
          <h2 className="font-bricolage font-medium text-[36px] sm:text-[48px] lg:text-[56px] leading-[1.1em] tracking-[-0.04em] m-0">
            Every logo, crafted from scratch
          </h2>
          <p className="font-bricolage font-medium text-base sm:text-lg leading-7 tracking-[-0.02em] text-white/50 m-0">
            No templates, no clip art. Every logo is uniquely generated by AI,
            just for your brand.
          </p>
        </div>

        <CategoryTabs active={active} onSelect={handleSelect} />

        <LogoGrid images={getCategoryImages(active)} animKey={animKey} />
      </div>
    </section>
  )
}
