'use client'

// Examples — category-tab logo gallery (mirrors the homepage Real Examples
// section), blind test, and bottom CTA.

import { useState } from 'react'
import Image from 'next/image'
import LSection from '../_components/LSection'
import LSectionHeader from '../_components/LSectionHeader'
import LBottomCTA from '../_components/LBottomCTA'
import { CATEGORIES, getCategoryImages, getLogosClaimed } from '@/data'

function CategoryPill({
  label,
  active,
  onClick,
}: {
  label: string
  active: boolean
  onClick: () => void
}) {
  const [hovered, setHovered] = useState(false)
  return (
    <button
      type="button"
      onClick={onClick}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      className="flex-shrink-0 cursor-pointer"
      style={{
        padding: '10px 18px',
        borderRadius: 9999,
        border: active
          ? '1px solid #7543E3'
          : hovered
          ? '1px solid rgba(33,3,64,0.35)'
          : '1px solid rgba(33,3,64,0.12)',
        background: active
          ? '#7543E3'
          : hovered
          ? 'rgba(117,67,227,0.06)'
          : '#FFFFFF',
        color: active ? '#FFFFFF' : hovered ? '#15141A' : 'rgba(21,20,26,0.7)',
        fontFamily: "'Mozilla Text', sans-serif",
        fontSize: '15px',
        lineHeight: 1,
        fontWeight: active ? 600 : 500,
        transition: 'all 0.15s ease',
        whiteSpace: 'nowrap',
      }}
    >
      {label}
    </button>
  )
}

export default function ExamplesPage() {
  const [activeCategory, setActiveCategory] = useState<string>('restaurant')
  const [galleryKey, setGalleryKey] = useState(0)
  const galleryImages = getCategoryImages(activeCategory)

  return (
    <main>
      {/* Local fade-in animation for logo grid (mirrors homepage). */}
      <style>{`
        @keyframes lLogoFade {
          to { opacity: 1; transform: translateY(0) scale(1); }
        }
      `}</style>

      {/* Hero — Our Story pattern */}
      <LSection hero>
        <div className="max-w-[900px] mx-auto flex flex-col items-center text-center">
          <h1 className="dk-h1 mb-5" style={{ color: '#15141A' }}>Examples</h1>
          <p className="dk-body-lg mb-4" style={{ color: '#7543E3', fontWeight: 500 }}>
            See what LOGO.AI designs
          </p>
          <p className="dk-body-lg max-w-[680px] mb-4" style={{ color: 'rgba(21,20,26,0.7)' }}>
            Every logo below was generated by AI in under 60 seconds. No human touch-ups. No templates. No stock assets.
          </p>
          <p className="dk-body-lg" style={{ color: '#15141A', fontWeight: 500 }}>
            Just AI, trained on real design principles, designing for real brands.
          </p>
        </div>
      </LSection>

      {/* By industry — category tabs + 12-image fade-in grid (homepage pattern) */}
      <LSection tone="alt">
        <LSectionHeader eyebrow="By industry" title="Explore logos across categories" />

        {/* Tabs — horizontal scroll on mobile with right-edge fade, wrap on desktop */}
        <div className="relative mb-10">
          <div
            className="md:hidden absolute right-0 top-0 bottom-0 w-10 pointer-events-none z-10"
            style={{ background: 'linear-gradient(to right, transparent, #F5F0FF)' }}
            aria-hidden="true"
          />
          <div
            className="flex md:flex-wrap md:justify-center gap-2.5 overflow-x-auto md:overflow-visible l-noscrollbar pb-1 md:pb-0 -mx-5 px-5 md:mx-0 md:px-0"
            style={{ WebkitOverflowScrolling: 'touch' }}
          >
            {CATEGORIES.map((cat) => (
              <CategoryPill
                key={cat.key}
                label={cat.name}
                active={cat.key === activeCategory}
                onClick={() => {
                  if (cat.key === activeCategory) return
                  setActiveCategory(cat.key)
                  setGalleryKey((k) => k + 1)
                }}
              />
            ))}
          </div>
        </div>

        {/* Logo grid — 12 per category, fade-in stagger on switch */}
        <div key={galleryKey} className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 md:gap-5 max-w-[1100px] mx-auto">
          {galleryImages.map((src, i) => (
            <div
              key={src}
              className="relative w-full overflow-hidden rounded-2xl group"
              style={{
                paddingBottom: '100%',
                background: '#FFFFFF',
                border: '1px solid rgba(32,18,58,0.06)',
                opacity: 0,
                transform: 'translateY(12px) scale(0.97)',
                animation: `lLogoFade 0.5s cubic-bezier(0.23,1,0.32,1) ${i * 0.04}s forwards`,
              }}
            >
              <Image
                src={src}
                alt=""
                fill
                className="object-cover transition-transform duration-[400ms] group-hover:scale-[1.04]"
                sizes="(max-width: 768px) 50vw, (max-width: 1024px) 33vw, 25vw"
                loading={i < 4 ? 'eager' : 'lazy'}
              />
            </div>
          ))}
        </div>
      </LSection>

      {/* The blind test */}
      <LSection>
        <LSectionHeader eyebrow="The blind test" title="Can you tell which ones are AI?" />
        <div className="max-w-[720px] mx-auto flex flex-col gap-5 text-center">
          <p className="dk-body-lg m-0" style={{ color: 'rgba(21,20,26,0.7)' }}>
            Every logo on this page was generated by LOGO.AI in under 60 seconds.
          </p>
          <p className="dk-body-lg m-0" style={{ color: 'rgba(21,20,26,0.7)' }}>
            We showed these to professional designers and asked them to pick which ones were AI-generated. The results: they guessed at roughly chance — no better than flipping a coin.
          </p>
          <p className="dk-body-lg m-0" style={{ color: '#15141A', fontWeight: 500 }}>
            That&apos;s the bar we set. That&apos;s the bar we cleared.
          </p>
        </div>
      </LSection>

      <LBottomCTA
        title="Every logo starts the same way — with your brand name and a short description."
        body={`In 60 seconds, you'll have logos designed specifically for your business. Just like the ones above. ${getLogosClaimed().toLocaleString('en-US')}+ founders have already claimed their spot. Two million free logos at launch — first come, first served.`}
      />
    </main>
  )
}
