'use client'

// Examples — see what LOGO.AI designs. Industries grid + blind test + CTA.
// Copy verbatim from CONTENT/NEW/EXAMPLES.docx.

import Link from 'next/link'
import { ArrowRight } from '@phosphor-icons/react'
import LSection from '../_components/LSection'
import LSectionHeader from '../_components/LSectionHeader'
import LBottomCTA from '../_components/LBottomCTA'
import { getLogosClaimed } from '@/data'

const INDUSTRIES = [
  'Restaurants', 'Coffee shops', 'Bakeries', 'Food trucks',
  'Barbershops', 'Hair salons', 'Nail studios', 'Boutiques',
  'Clothing brands', 'Gyms', 'Cleaning services', 'Landscaping',
  'Pet grooming', 'E-commerce', 'Content creators', 'Tattoo studios',
]

export default function ExamplesPage() {
  return (
    <main>
      {/* Hero — Our Story pattern */}
      <LSection>
        <div className="max-w-[900px] mx-auto flex flex-col items-center text-center">
          <h1 className="dk-h1 mb-5" style={{ color: '#15141A' }}>Examples</h1>
          <p className="dk-body-lg mb-4" style={{ color: '#7543E3', fontWeight: 500 }}>
            See what LOGO.AI designs
          </p>
          <p className="dk-body-lg max-w-[680px] mb-4" style={{ color: 'rgba(21,20,26,0.7)' }}>
            Every logo below was generated by AI in under 60 seconds. No human touch-ups. No templates. No stock assets.
          </p>
          <p className="dk-body-lg" style={{ color: '#15141A', fontWeight: 500 }}>
            Just AI, trained on real design principles, designing for real brands.
          </p>
        </div>
      </LSection>

      {/* By industry — horizontal scroll on mobile, grid from sm and up */}
      <LSection tone="alt">
        <LSectionHeader eyebrow="By industry" title="Explore logos across categories" />
        {/* Mobile: horizontal scroll strip */}
        <div
          className="sm:hidden -mx-5 px-5 overflow-x-auto"
          style={{ scrollbarWidth: 'none', WebkitOverflowScrolling: 'touch' }}
        >
          <div className="flex gap-3 pb-2" style={{ width: 'max-content' }}>
            {INDUSTRIES.map((i) => (
              <div
                key={i}
                className="l-card-hover flex-shrink-0"
                style={{
                  background: '#FFFFFF',
                  borderRadius: 16,
                  width: 140,
                  height: 140,
                  border: '1px solid rgba(32,18,58,0.08)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  padding: 16,
                  textAlign: 'center',
                  cursor: 'pointer',
                }}
              >
                <p className="dk-body m-0" style={{ color: '#15141A', fontWeight: 500 }}>{i}</p>
              </div>
            ))}
          </div>
        </div>
        {/* sm+: grid */}
        <div className="hidden sm:grid max-w-[920px] mx-auto grid-cols-3 md:grid-cols-4 gap-4">
          {INDUSTRIES.map((i) => (
            <div
              key={i}
              className="l-card-hover"
              style={{
                background: '#FFFFFF',
                borderRadius: 16,
                aspectRatio: '1',
                border: '1px solid rgba(32,18,58,0.08)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                padding: 20,
                textAlign: 'center',
                cursor: 'pointer',
              }}
            >
              <p className="dk-body-lg m-0" style={{ color: '#15141A', fontWeight: 500 }}>{i}</p>
            </div>
          ))}
        </div>
      </LSection>

      {/* The blind test */}
      <LSection>
        <LSectionHeader eyebrow="The blind test" title="Can you tell which ones are AI?" />
        <div className="max-w-[720px] mx-auto flex flex-col gap-5 text-center">
          <p className="dk-body-lg m-0" style={{ color: 'rgba(21,20,26,0.7)' }}>
            Every logo on this page was generated by LOGO.AI in under 60 seconds.
          </p>
          <p className="dk-body-lg m-0" style={{ color: 'rgba(21,20,26,0.7)' }}>
            We showed these to professional designers and asked them to pick which ones were AI-generated. The results: they guessed at roughly chance — no better than flipping a coin.
          </p>
          <p className="dk-body-lg m-0" style={{ color: '#15141A', fontWeight: 500 }}>
            That&apos;s the bar we set. That&apos;s the bar we cleared.
          </p>
        </div>
      </LSection>

      <LBottomCTA
        title="Every logo starts the same way — with your brand name and a short description."
        body={`In 60 seconds, you'll have logos designed specifically for your business. Just like the ones above. ${getLogosClaimed().toLocaleString('en-US')}+ founders have already claimed their spot. Two million free logos at launch — first come, first served.`}
      />
    </main>
  )
}
