'use client'

// Examples — see what LOGO.AI designs. Industries grid + blind test + CTA.
// Copy verbatim from CONTENT/NEW/EXAMPLES.docx.

import Link from 'next/link'
import { ArrowRight } from '@phosphor-icons/react'
import LSection from '../_components/LSection'
import LSectionHeader from '../_components/LSectionHeader'
import LBottomCTA from '../_components/LBottomCTA'
import { getLogosClaimed } from '@/data'

type Industry = { name: string; img: string }
const INDUSTRIES: Industry[] = [
  { name: 'Restaurants',       img: '/Images/Logos/restaurant-logo-1.webp' },
  { name: 'Coffee shops',      img: '/Images/Logos/coffee-shop-logo-1.webp' },
  { name: 'Bakeries',          img: '/Images/Logos/bakery-logo-1.webp' },
  { name: 'Food trucks',       img: '/Images/Logos/food-truck-logo-1.webp' },
  { name: 'Barbershops',       img: '/Images/Logos/barbershop-logo-1.webp' },
  { name: 'Hair salons',       img: '/Images/Logos/hair-salon-logo-1.webp' },
  { name: 'Nail studios',      img: '/Images/Logos/nail-studio-logo-1.webp' },
  { name: 'Boutiques',         img: '/Images/Logos/boutique-logo-1.webp' },
  { name: 'Clothing brands',   img: '/Images/Logos/clothing-brand-logo-1.webp' },
  { name: 'Gyms',              img: '/Images/Logos/gym-logo-1.webp' },
  { name: 'Cleaning services', img: '/Images/Logos/cleaning-service-logo-1.webp' },
  { name: 'Landscaping',       img: '/Images/Logos/landscaping-company-logo-1.webp' },
  { name: 'Pet grooming',      img: '/Images/Logos/pet-grooming-logo-1.webp' },
  { name: 'E-commerce',        img: '/Images/Logos/e-commerce-brand-logo-7.webp' },
  { name: 'Content creators',  img: '/Images/Logos/content-creator-logo-1.webp' },
  { name: 'Tattoo studios',    img: '/Images/Logos/tattoo-studio-logo-1.webp' },
]

export default function ExamplesPage() {
  return (
    <main>
      {/* Hero — Our Story pattern */}
      <LSection>
        <div className="max-w-[900px] mx-auto flex flex-col items-center text-center">
          <h1 className="dk-h1 mb-5" style={{ color: '#15141A' }}>Examples</h1>
          <p className="dk-body-lg mb-4" style={{ color: '#7543E3', fontWeight: 500 }}>
            See what LOGO.AI designs
          </p>
          <p className="dk-body-lg max-w-[680px] mb-4" style={{ color: 'rgba(21,20,26,0.7)' }}>
            Every logo below was generated by AI in under 60 seconds. No human touch-ups. No templates. No stock assets.
          </p>
          <p className="dk-body-lg" style={{ color: '#15141A', fontWeight: 500 }}>
            Just AI, trained on real design principles, designing for real brands.
          </p>
        </div>
      </LSection>

      {/* By industry — horizontal scroll on mobile, grid from sm and up */}
      <LSection tone="alt">
        <LSectionHeader eyebrow="By industry" title="Explore logos across categories" />
        {/* Mobile: horizontal scroll strip */}
        <div
          className="sm:hidden -mx-5 px-5 overflow-x-auto"
          style={{ scrollbarWidth: 'none', WebkitOverflowScrolling: 'touch' }}
        >
          <div className="flex gap-3 pb-2" style={{ width: 'max-content' }}>
            {INDUSTRIES.map((i) => (
              <div
                key={i.name}
                className="l-card-hover flex-shrink-0 relative overflow-hidden"
                style={{
                  borderRadius: 16,
                  width: 160,
                  aspectRatio: '1',
                  border: '1px solid rgba(32,18,58,0.08)',
                  cursor: 'pointer',
                  backgroundImage: `url('${i.img}')`,
                  backgroundSize: 'cover',
                  backgroundPosition: 'center',
                  backgroundColor: '#F5F0FF',
                }}
              >
                <div
                  className="absolute inset-x-0 bottom-0 flex items-end justify-center"
                  style={{
                    height: '55%',
                    background: 'linear-gradient(to bottom, rgba(0,0,0,0) 0%, rgba(0,0,0,0.55) 60%, rgba(0,0,0,0.78) 100%)',
                    padding: '0 10px 12px 10px',
                  }}
                >
                  <p
                    className="dk-caption m-0"
                    style={{
                      color: '#FFFFFF',
                      fontWeight: 600,
                      textAlign: 'center',
                      textShadow: '0 1px 4px rgba(0,0,0,0.45)',
                    }}
                  >
                    {i.name}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
        {/* sm+: grid */}
        <div className="hidden sm:grid max-w-[920px] mx-auto grid-cols-3 md:grid-cols-4 gap-4">
          {INDUSTRIES.map((i) => (
            <div
              key={i.name}
              className="l-card-hover relative overflow-hidden"
              style={{
                borderRadius: 16,
                aspectRatio: '1',
                border: '1px solid rgba(32,18,58,0.08)',
                cursor: 'pointer',
                backgroundImage: `url('${i.img}')`,
                backgroundSize: 'cover',
                backgroundPosition: 'center',
                backgroundColor: '#F5F0FF',
              }}
            >
              <div
                className="absolute inset-x-0 bottom-0 flex items-end justify-center"
                style={{
                  height: '50%',
                  background: 'linear-gradient(to bottom, rgba(0,0,0,0) 0%, rgba(0,0,0,0.55) 60%, rgba(0,0,0,0.78) 100%)',
                  padding: '0 12px 16px 12px',
                }}
              >
                <p
                  className="dk-body m-0"
                  style={{
                    color: '#FFFFFF',
                    fontWeight: 600,
                    textAlign: 'center',
                    textShadow: '0 1px 6px rgba(0,0,0,0.5)',
                  }}
                >
                  {i.name}
                </p>
              </div>
            </div>
          ))}
        </div>
      </LSection>

      {/* The blind test */}
      <LSection>
        <LSectionHeader eyebrow="The blind test" title="Can you tell which ones are AI?" />
        <div className="max-w-[720px] mx-auto flex flex-col gap-5 text-center">
          <p className="dk-body-lg m-0" style={{ color: 'rgba(21,20,26,0.7)' }}>
            Every logo on this page was generated by LOGO.AI in under 60 seconds.
          </p>
          <p className="dk-body-lg m-0" style={{ color: 'rgba(21,20,26,0.7)' }}>
            We showed these to professional designers and asked them to pick which ones were AI-generated. The results: they guessed at roughly chance — no better than flipping a coin.
          </p>
          <p className="dk-body-lg m-0" style={{ color: '#15141A', fontWeight: 500 }}>
            That&apos;s the bar we set. That&apos;s the bar we cleared.
          </p>
        </div>
      </LSection>

      <LBottomCTA
        title="Every logo starts the same way — with your brand name and a short description."
        body={`In 60 seconds, you'll have logos designed specifically for your business. Just like the ones above. ${getLogosClaimed().toLocaleString('en-US')}+ founders have already claimed their spot. Two million free logos at launch — first come, first served.`}
      />
    </main>
  )
}
