'use client'

// Press & Media — quick facts, releases, press kit, brand assets, usage guidelines.
// Copy verbatim from CONTENT/NEW/PRESS.docx.

import LSection from '../_components/LSection'
import LSectionHeader from '../_components/LSectionHeader'
import LBottomCTA from '../_components/LBottomCTA'
import { getLogosClaimed } from '@/data'

const QUICK_FACTS = [
  { label: 'Founded',          value: '2024' },
  { label: 'Headquarters',     value: 'San Francisco' },
  { label: 'Additional teams', value: 'Singapore, Tallinn, Dubai' },
  { label: 'Stage',            value: 'Pre-launch (claims open)' },
  { label: 'Launch',           value: 'June 2026' },
]

function getPressReleases() {
  const claimed = getLogosClaimed().toLocaleString('en-US')
  return [
    {
      status: 'Live Now',
      title: 'LOGO.AI Opens Claims for 2,000,000 Free AI-Generated Logos',
      body: `LOGO.AI is now accepting claims for two million free logos ahead of its June 2026 launch. Each logo is uniquely generated by AI — not pulled from a template library. The largest free logo giveaway in design history, available first-come, first-served. Over ${claimed} founders have already claimed their spot.`,
    },
    {
      status: 'Live Now',
      title: 'LOGO.AI Secures Premium Domain as AI Design Category Heats Up',
      body: "The acquisition of LOGO.AI signals growing confidence in AI-first design tools — and the company's commitment to owning the category.",
    },
    {
      status: 'Coming at Launch',
      title: 'How LOGO.AI Is Redefining Brand Identity for Startups',
      body: 'A look at the technology behind LOGO.AI — and why founders are choosing AI-generated logos over traditional design agencies.',
    },
  ]
}

const PRESS_KIT_DESCRIPTIONS = [
  {
    label: 'Short version',
    body: 'LOGO.AI is an AI-powered logo generator launching June 2026. It designs professional, original logos in under sixty seconds. 2,000,000 free logos available to claim now. No credit card required.',
  },
  {
    label: 'Medium version',
    body: "LOGO.AI is an AI-powered logo generator launching June 2026. Unlike template-based tools, it's trained on real design principles — color theory, typography pairing, negative space — to generate original, studio-quality logos in 60 seconds. 2,000,000 free logos available at launch, with a paid brand kit for founders who want the full package.",
  },
  {
    label: 'Full version',
    body: 'LOGO.AI is an AI logo generator launching June 2026, with claims open now. The platform designs professional, original logos in under sixty seconds using proprietary AI trained on real design principles — color theory, typography pairing, negative space, and visual hierarchy. Unlike traditional logo makers that recombine templates, LOGO.AI generates unique designs tailored to each brand. The company is headquartered in San Francisco, with teams in Singapore, Tallinn, and Dubai. 2,000,000 free logos are being offered at launch on a first-come, first-served basis, with a full paid brand kit — app icons, social kits, business cards, letterhead, mockups, and more — available alongside.',
  },
]

const PULL_QUOTES = [
  {
    quote: "Every brand deserves to look like a million bucks on day one. That's not a nice-to-have anymore — it's table stakes. We just made it free.",
    attribution: 'Ashwin Reddy — Co-Founder',
  },
  {
    quote: "Most people don't need a brand agency. They need one great logo and the confidence to move forward. That's the unlock we're building.",
    attribution: 'Abhinav Reddy — Co-Founder',
  },
]

const BRAND_COLORS = [
  { hex: '#7543E3', name: 'Purple Heart · Primary' },
  { hex: '#6132BC', name: 'Purple Heart Dark' },
  { hex: '#C7A8FF', name: 'Mauve' },
  { hex: '#E0CAFF', name: 'Lighter Mauve' },
  { hex: '#F5F0FF', name: 'Section Alt BG' },
  { hex: '#210340', name: 'Tolopea · Dark BG' },
  { hex: '#15141A', name: 'Woodsmoke · Body' },
  { hex: '#FFFFFF', name: 'White' },
]

const DO_LIST = [
  'Use the official logo files from our press kit',
  "Maintain clear space around the logo equal to the height of the 'L'",
  'Use the white logo on dark backgrounds',
  'Use the dark logo on light backgrounds',
  'Link back to logo.ai when featuring the brand',
]

const DONT_LIST = [
  'Alter the logo colors or apply gradients',
  'Stretch, rotate, or distort the logo',
  'Add drop shadows, outlines, or effects',
  'Place the logo on busy or low-contrast backgrounds',
  'Use the logo to imply endorsement without permission',
]

export default function PressPage() {
  return (
    <main>
      {/* Hero — Our Story pattern */}
      <LSection>
        <div className="max-w-[900px] mx-auto flex flex-col items-center text-center">
          <h1 className="dk-h1 mb-5" style={{ color: '#15141A' }}>Press &amp; Media</h1>
          <p className="dk-body-lg mb-4" style={{ color: '#7543E3', fontWeight: 500 }}>
            Everything you need to cover LOGO.AI
          </p>
          <p className="dk-body-lg max-w-[680px] mb-4" style={{ color: 'rgba(21,20,26,0.7)' }}>
            Brand assets, company facts, press releases, and media guidelines — all in one place.
          </p>
          <p className="dk-body-lg" style={{ color: '#15141A', fontWeight: 500 }}>
            For press inquiries: <a href="mailto:press@logo.ai" className="l-link">press@logo.ai</a> (response within 24 hours)
          </p>
        </div>
      </LSection>

      {/* Quick facts */}
      <LSection tone="alt">
        <LSectionHeader eyebrow="Company overview" title="Quick facts" />
        <div
          className="max-w-[820px] mx-auto"
          style={{
            display: 'flex',
            flexWrap: 'wrap',
            justifyContent: 'center',
            gap: 20,
          }}
        >
          {QUICK_FACTS.map((f, i) => (
            <div
              key={i}
              style={{
                background: '#FFFFFF',
                borderRadius: 16,
                padding: 24,
                border: '1px solid rgba(32,18,58,0.08)',
                flex: '1 1 240px',
                maxWidth: 280,
                minWidth: 220,
              }}
            >
              <p className="dk-caption m-0 mb-2" style={{ color: '#7543E3', textTransform: 'uppercase', letterSpacing: '0.06em', fontWeight: 600 }}>
                {f.label}
              </p>
              <p className="dk-body-lg m-0" style={{ color: '#15141A', fontWeight: 500 }}>
                {f.value}
              </p>
            </div>
          ))}
        </div>
      </LSection>

      {/* Press releases */}
      <LSection>
        <LSectionHeader eyebrow="Press releases" title="Latest announcements" />
        <div className="max-w-[820px] mx-auto flex flex-col gap-5">
          {getPressReleases().map((r, i) => (
            <div
              key={i}
              style={{
                background: '#F5F0FF',
                borderRadius: 16,
                padding: 32,
                border: '1px solid rgba(32,18,58,0.08)',
              }}
            >
              <span
                className="dk-caption inline-block mb-3"
                style={{
                  color: r.status === 'Live Now' ? '#7543E3' : 'rgba(21,20,26,0.55)',
                  textTransform: 'uppercase',
                  letterSpacing: '0.06em',
                  fontWeight: 600,
                }}
              >
                {r.status}
              </span>
              <h3 className="dk-h3 mb-3" style={{ color: '#15141A' }}>{r.title}</h3>
              <p className="dk-body-lg m-0" style={{ color: 'rgba(21,20,26,0.7)' }}>{r.body}</p>
            </div>
          ))}
        </div>
      </LSection>

      {/* Press kit descriptions */}
      <LSection tone="alt">
        <LSectionHeader eyebrow="Press kit descriptions" title="Drop these straight into your article" />
        <div className="max-w-[820px] mx-auto flex flex-col gap-5">
          {PRESS_KIT_DESCRIPTIONS.map((d, i) => (
            <div
              key={i}
              style={{
                background: '#FFFFFF',
                borderRadius: 16,
                padding: 32,
                border: '1px solid rgba(32,18,58,0.08)',
              }}
            >
              <p className="dk-caption m-0 mb-3" style={{ color: '#7543E3', textTransform: 'uppercase', letterSpacing: '0.06em', fontWeight: 600 }}>
                {d.label}
              </p>
              <p className="dk-body-lg m-0" style={{ color: '#15141A' }}>{d.body}</p>
            </div>
          ))}
          <div className="max-w-[720px] mx-auto text-center mt-2">
            <p className="dk-body-lg m-0" style={{ color: 'rgba(21,20,26,0.7)' }}>
              In a sentence: <span style={{ color: '#15141A', fontWeight: 500, fontStyle: 'italic' }}>&ldquo;LOGO.AI creates professional logos in seconds.&rdquo;</span>
            </p>
          </div>
        </div>
      </LSection>

      {/* Pull quotes */}
      <LSection>
        <LSectionHeader eyebrow="Pull quotes" title="Ready-to-use quotes from our founders" />
        <div
          className="max-w-[900px] mx-auto"
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
            gap: 24,
          }}
        >
          {PULL_QUOTES.map((q, i) => (
            <blockquote
              key={i}
              className="m-0 p-0"
              style={{
                background: '#F5F0FF',
                borderRadius: 16,
                padding: 32,
                border: '1px solid rgba(32,18,58,0.08)',
                borderLeft: '3px solid #7543E3',
              }}
            >
              <p className="dk-body-lg mb-4" style={{ color: '#15141A', fontStyle: 'italic' }}>
                &ldquo;{q.quote}&rdquo;
              </p>
              <p className="dk-caption m-0" style={{ color: 'rgba(21,20,26,0.6)' }}>
                {q.attribution}
              </p>
            </blockquote>
          ))}
        </div>
      </LSection>

      {/* Brand assets */}
      <LSection tone="alt">
        <LSectionHeader eyebrow="Brand assets" title="Logo, colors, and typography" />
        <div className="max-w-[820px] mx-auto">
          <p className="dk-body-lg text-center mb-10" style={{ color: 'rgba(21,20,26,0.7)' }}>
            Official brand assets for editorial use. All files print- and web-ready.
          </p>

          {/* Logo Files */}
          <div
            style={{
              background: '#FFFFFF',
              borderRadius: 16,
              padding: 32,
              border: '1px solid rgba(32,18,58,0.08)',
              marginBottom: 20,
            }}
          >
            <h3 className="dk-h3 mb-3" style={{ color: '#15141A' }}>Logo Files</h3>
            <p className="dk-body-lg m-0" style={{ color: 'rgba(21,20,26,0.7)' }}>
              Official wordmark: <strong style={{ color: '#15141A' }}>LOGO<span style={{ color: '#7543E3' }}>.</span>AI</strong> in DM Serif Display. Dark and light variants with transparent backgrounds — purple dot accent preserved.
            </p>
          </div>

          {/* Brand Colors */}
          <div
            style={{
              background: '#FFFFFF',
              borderRadius: 16,
              padding: 32,
              border: '1px solid rgba(32,18,58,0.08)',
              marginBottom: 20,
            }}
          >
            <h3 className="dk-h3 mb-5" style={{ color: '#15141A' }}>Brand Colors</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {BRAND_COLORS.map((c, i) => (
                <div key={i} className="flex items-center gap-3">
                  <span
                    style={{
                      width: 40,
                      height: 40,
                      borderRadius: 8,
                      background: c.hex,
                      border: '1px solid rgba(32,18,58,0.08)',
                      flexShrink: 0,
                    }}
                    aria-hidden="true"
                  />
                  <div>
                    <p className="dk-body m-0" style={{ color: '#15141A', fontWeight: 600 }}>{c.hex}</p>
                    <p className="dk-caption m-0" style={{ color: 'rgba(21,20,26,0.6)' }}>{c.name}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Typography */}
          <div
            style={{
              background: '#FFFFFF',
              borderRadius: 16,
              padding: 32,
              border: '1px solid rgba(32,18,58,0.08)',
            }}
          >
            <h3 className="dk-h3 mb-4" style={{ color: '#15141A' }}>Typography</h3>
            <div className="flex flex-col gap-3">
              <div>
                <p className="dk-body-lg m-0" style={{ color: '#15141A' }}>
                  <strong>Wordmark:</strong> DM Serif Display
                </p>
                <p className="dk-caption m-0" style={{ color: 'rgba(21,20,26,0.65)' }}>
                  Used only for LOGO.AI — 400 (single weight).
                </p>
              </div>
              <div>
                <p className="dk-body-lg m-0" style={{ color: '#15141A' }}>
                  <strong>Headlines:</strong> Mozilla Headline
                </p>
                <p className="dk-caption m-0" style={{ color: 'rgba(21,20,26,0.65)' }}>
                  Weights: 300–700 variable. Used at 600 for h1/h2/h3.
                </p>
              </div>
              <div>
                <p className="dk-body-lg m-0" style={{ color: '#15141A' }}>
                  <strong>Body:</strong> Mozilla Text
                </p>
                <p className="dk-caption m-0" style={{ color: 'rgba(21,20,26,0.65)' }}>
                  Weights: 400–700 + italics. Used for nav, body copy, captions, CTAs.
                </p>
              </div>
            </div>
          </div>
        </div>
      </LSection>

      {/* Usage guidelines */}
      <LSection>
        <LSectionHeader eyebrow="Usage guidelines" title="How to use our brand" />
        <div className="max-w-[820px] mx-auto">
          <p className="dk-body-lg text-center mb-10" style={{ color: 'rgba(21,20,26,0.7)' }}>
            Please follow these guidelines when featuring LOGO.AI in editorial or media contexts.
          </p>

          {/* How to write our name */}
          <div
            style={{
              background: '#F5F0FF',
              borderRadius: 16,
              padding: 32,
              border: '1px solid rgba(32,18,58,0.08)',
              marginBottom: 24,
            }}
          >
            <h3 className="dk-h3 mb-3" style={{ color: '#15141A' }}>How to write our name</h3>
            <p className="dk-body-lg mb-2" style={{ color: '#15141A' }}>
              Always write as <strong>LOGO.AI</strong> — all caps, period between LOGO and AI.
            </p>
            <p className="dk-body-lg m-0" style={{ color: 'rgba(21,20,26,0.7)' }}>
              ✅ LOGO.AI &nbsp;&nbsp; ❌ LogoAI · logoai · Logo AI · Logo.ai · Logo.Ai
            </p>
          </div>

          {/* Do / Don't */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
            <div
              style={{
                background: '#FFFFFF',
                borderRadius: 16,
                padding: 32,
                border: '1px solid rgba(32,18,58,0.08)',
              }}
            >
              <p className="dk-caption m-0 mb-4" style={{ color: '#7543E3', textTransform: 'uppercase', letterSpacing: '0.06em', fontWeight: 600 }}>
                Do
              </p>
              <ul className="flex flex-col gap-3 list-none p-0 m-0">
                {DO_LIST.map((d, i) => (
                  <li key={i} className="dk-body flex items-start gap-2" style={{ color: '#15141A' }}>
                    <span style={{ color: '#7543E3', flexShrink: 0 }} aria-hidden="true">✓</span>
                    <span>{d}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div
              style={{
                background: '#FFFFFF',
                borderRadius: 16,
                padding: 32,
                border: '1px solid rgba(32,18,58,0.08)',
              }}
            >
              <p className="dk-caption m-0 mb-4" style={{ color: 'rgba(21,20,26,0.55)', textTransform: 'uppercase', letterSpacing: '0.06em', fontWeight: 600 }}>
                Don&apos;t
              </p>
              <ul className="flex flex-col gap-3 list-none p-0 m-0">
                {DONT_LIST.map((d, i) => (
                  <li key={i} className="dk-body flex items-start gap-2" style={{ color: '#15141A' }}>
                    <span style={{ color: 'rgba(21,20,26,0.55)', flexShrink: 0 }} aria-hidden="true">✕</span>
                    <span>{d}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </LSection>

      <LBottomCTA
        title="For interview requests, embargoed materials, early product access, or custom brand assets"
        body="Our media team is here to help."
        ctaLabel="press@logo.ai"
        ctaHref="mailto:press@logo.ai"
        external
        caption="Response within 24 hours"
      />
    </main>
  )
}
