import PageWrapper from '@/components/PageWrapper'
import PageSection from '@/components/ui/PageSection'
import Badge from '@/components/ui/Badge'
import { BLUE, BORDER, CARD_BG } from '@/lib/ds'

const PRESS_RELEASES = [
  {
    tag: 'Launch',
    title: 'LOGO.AI Launches with 2,000,000 Free AI-Generated Logos',
    desc: 'LOGO.AI opens its doors with one million free logos — each one uniquely generated by AI, not pulled from a library. The largest free logo giveaway in design history.',
    icon: (
      <svg width="20" height="20" viewBox="0 0 256 256" fill="none" stroke={BLUE} strokeWidth="20" strokeLinecap="round" strokeLinejoin="round">
        <polyline points="152,16 72,144 128,144 104,240 184,112 128,112 152,16"/>
      </svg>
    ),
  },
  {
    tag: 'Product',
    title: 'How LOGO.AI Is Redefining Brand Identity for Startups',
    desc: 'A deep dive into the technology behind LOGO.AI and why founders are choosing AI-generated logos over traditional design agencies.',
    icon: (
      <svg width="20" height="20" viewBox="0 0 256 256" fill="none" stroke={BLUE} strokeWidth="20" strokeLinecap="round" strokeLinejoin="round">
        <rect x="32" y="48" width="192" height="144" rx="16"/>
        <line x1="160" y1="224" x2="96" y2="224"/>
        <line x1="128" y1="192" x2="128" y2="224"/>
      </svg>
    ),
  },
  {
    tag: 'Company',
    title: 'LOGO.AI Secures Premium Domain as AI Design Category Heats Up',
    desc: "The acquisition of LOGO.AI signals growing confidence in AI-first design tools and the company's commitment to owning the category.",
    icon: (
      <svg width="20" height="20" viewBox="0 0 256 256" fill="none" stroke={BLUE} strokeWidth="20" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="128" cy="128" r="96"/>
        <line x1="32" y1="128" x2="224" y2="128"/>
        <ellipse cx="128" cy="128" rx="40" ry="96"/>
      </svg>
    ),
  },
]

const QUOTES = [
  {
    quote: "Every brand deserves to look like a million bucks on day one. That's not a nice-to-have anymore — it's table stakes. We just made it free.",
    name: 'Ashwin Reddy',
    role: 'Co-founder — Strategy & Growth',
  },
  {
    quote: "Most people don't need a brand agency. They need one great logo and the confidence to move forward. That's the unlock we're building.",
    name: 'Abhinav Reddy',
    role: 'Co-founder — Product & Technology',
  },
]

const GUIDELINES_DO = [
  'Use the official logo files provided in the press kit',
  "Maintain clear space around the logo equal to the height of the 'L'",
  'Use the white logo version on dark backgrounds',
  'Use the dark logo version on light backgrounds',
  'Link back to logo.ai when featuring the brand',
]

const GUIDELINES_DONT = [
  'Alter the logo colors or apply gradients',
  'Stretch, rotate, or distort the logo',
  'Add drop shadows, outlines, or effects',
  'Place the logo on busy or low-contrast backgrounds',
  'Use the logo to imply endorsement without permission',
]

const STATS = [
  { n: '2024', label: 'Founded' },
  { n: 'SF', label: 'Headquarters' },
  { n: '4', label: 'Countries' },
  { n: 'Pre-Launch', label: 'Stage' },
]

export default function PressPage() {
  return (
    <PageWrapper>
      {/* ── Hero ── */}
      <section className="px-5 md:px-8 lg:px-10 pt-[140px] md:pt-[200px] pb-16 md:pb-[120px]">
        <div className="max-w-[95%] sm:max-w-[90%] mx-auto flex flex-col gap-6 items-center text-center">
          <h1
            className="font-bricolage font-medium leading-[1.08em] tracking-[-0.04em] m-0 max-w-[800px]"
            style={{ fontSize: 'clamp(36px, 5.5vw, 72px)' }}
          >
            Press
          </h1>
          <p className="font-bricolage font-medium text-xl md:text-2xl leading-[1.4em] tracking-[-0.02em] text-white/70 max-w-[800px] m-0">
            Everything you need to cover LOGO.AI.
          </p>
          <p className="font-bricolage font-medium text-lg md:text-xl leading-[1.7em] tracking-[-0.02em] text-white/50 max-w-[580px] m-0">
            Brand assets, company facts, press releases, and media guidelines — all in one place.
          </p>
          <a
            href="mailto:press@logo.ai"
            className="inline-flex w-fit items-center gap-2 font-bricolage font-medium text-white no-underline transition-all duration-200 hover:bg-white hover:text-black"
            style={{ border: '1px solid rgba(255,255,255,0.2)', borderRadius: 8, padding: '12px 24px', fontSize: 16 }}
          >
            press@logo.ai
          </a>
        </div>
      </section>

      {/* ── Company Overview ── */}
      <PageSection compact tinted>
        <div className="max-w-[95%] sm:max-w-[90%] mx-auto flex flex-col items-center text-center gap-8">
            <Badge icon="buildings" text="Company Overview" />
            <div className="w-full grid grid-cols-2 md:grid-cols-4 gap-6">
              {STATS.map((s) => (
                <div key={s.label} className="flex flex-col gap-1.5">
                  <span className="font-bricolage font-bold text-[28px] md:text-[36px] leading-none tracking-[-0.03em]">{s.n}</span>
                  <span className="font-bricolage text-sm font-medium text-white/40">{s.label}</span>
                </div>
              ))}
            </div>
          </div>
      </PageSection>

      {/* ── Press Releases ── */}
      <PageSection>
        <div className="max-w-[95%] sm:max-w-[90%] mx-auto flex flex-col items-center text-center gap-10 md:gap-[60px]">
            <div className="flex flex-col items-center gap-3 max-w-[700px]">
              <Badge icon="newspaper" text="Press Releases" />
              <h2 className="font-bricolage font-medium text-[28px] md:text-[40px] leading-[1.15em] tracking-[-0.04em] m-0">
                Upcoming announcements
              </h2>
            </div>
            <div className="w-full flex flex-col gap-4 text-left">
              {PRESS_RELEASES.map((pr) => (
                <div
                  key={pr.title}
                  className="rounded-2xl p-7 md:p-8 flex flex-col gap-4"
                  style={{ border: '1px solid rgba(84,87,94,0.3)', background: 'rgba(255,255,255,0.015)' }}
                >
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex items-center gap-3">
                      <span
                        className="font-bricolage text-xs font-medium text-white/60 px-2.5 py-1 rounded-md"
                        style={{ background: 'rgba(51,106,234,0.15)', border: '1px solid rgba(51,106,234,0.25)' }}
                      >
                        {pr.tag}
                      </span>
                      <span
                        className="font-bricolage text-xs font-medium text-white/40 px-2.5 py-1 rounded-md"
                        style={{ background: 'rgba(255,255,255,0.05)' }}
                      >
                        Coming Soon
                      </span>
                    </div>
                    {pr.icon}
                  </div>
                  <h3 className="font-bricolage font-medium text-lg md:text-xl leading-[1.3em] m-0">{pr.title}</h3>
                  <p className="font-bricolage text-sm md:text-base leading-[1.7em] text-white/50 m-0">{pr.desc}</p>
                </div>
              ))}
            </div>
          </div>
      </PageSection>

      {/* ── For Journalists ── */}
      <PageSection>
        <div className="max-w-[95%] sm:max-w-[90%] mx-auto flex flex-col items-center text-center gap-10 md:gap-[60px]">
            <div className="flex flex-col items-center gap-3 max-w-[700px]">
              <Badge icon="article" text="For Journalists" />
              <h2 className="font-bricolage font-medium text-[28px] md:text-[40px] leading-[1.15em] tracking-[-0.04em] m-0">
                Copy-paste descriptions
              </h2>
            </div>
            <div className="w-full grid grid-cols-1 md:grid-cols-2 gap-5 text-left">
              {[
                {
                  label: 'Short version',
                  text: 'LOGO.AI is an AI-powered logo generator launching May 2026. The platform creates professional, original logos in seconds — not templates. 2,000,000 free logos will be available at launch, no credit card required.',
                },
                {
                  label: 'Full version',
                  text: 'LOGO.AI is an AI logo generator launching May 2026, founded by brothers Abhinav and Ashwin Reddy — serial founders with three decades of building products across web and mobile, multiple exits, and millions of users reached. The platform creates professional, original logos in seconds using AI trained on real design principles — color, typography, spacing, and hierarchy. Unlike traditional logo makers that recycle templates, LOGO.AI generates unique designs tailored to each brand. The company is headquartered in San Francisco, with teams in Singapore, Tallinn, and Dubai. At launch, 2,000,000 free logos will be available in high-resolution PNG, SVG, JPG, and PDF formats.',
                },
              ].map((item) => (
                <div
                  key={item.label}
                  className="rounded-2xl p-7 flex flex-col gap-4"
                  style={{ border: '1px solid rgba(84,87,94,0.3)' }}
                >
                  <p className="font-bricolage text-xs font-medium text-white/40 uppercase tracking-[2px] m-0">{item.label}</p>
                  <p className="font-bricolage text-sm md:text-base leading-[1.7em] text-white/50 m-0">{item.text}</p>
                </div>
              ))}
            </div>

            {/* Quotes */}
            <div className="w-full flex flex-col gap-4 text-left">
              <p className="font-bricolage text-xs font-medium text-white/40 uppercase tracking-[2px] m-0">Pull Quotes</p>
              <div className="w-full grid grid-cols-1 md:grid-cols-2 gap-5">
                {QUOTES.map((q) => (
                  <div
                    key={q.name}
                    className="rounded-2xl p-7 flex flex-col gap-5"
                    style={{ border: '1px solid rgba(84,87,94,0.3)', background: 'rgba(255,255,255,0.015)' }}
                  >
                    <p className="font-bricolage text-base md:text-lg leading-[1.6em] text-white/80 m-0 italic">
                      &ldquo;{q.quote}&rdquo;
                    </p>
                    <div className="flex flex-col gap-0.5 pt-2 border-t border-white/[0.06]">
                      <span className="font-bricolage font-medium text-sm text-white">{q.name}</span>
                      <span className="font-bricolage text-xs text-white/40">{q.role}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
      </PageSection>

      {/* ── Usage Guidelines ── */}
      <PageSection>
        <div className="max-w-[95%] sm:max-w-[90%] mx-auto flex flex-col items-center text-center gap-10 md:gap-[60px]">
            <div className="flex flex-col items-center gap-3 max-w-[700px]">
              <Badge icon="shield" text="Usage Guidelines" />
              <h2 className="font-bricolage font-medium text-[28px] md:text-[40px] leading-[1.15em] tracking-[-0.04em] m-0">
                How to use our brand
              </h2>
            </div>

            {/* Name usage */}
            <div
              className="w-full rounded-2xl p-7 flex flex-col gap-4 text-left"
              style={{ border: '1px solid rgba(84,87,94,0.3)' }}
            >
              <p className="font-bricolage text-xs font-medium text-white/40 uppercase tracking-[2px] m-0">How to write our name</p>
              <p className="font-bricolage text-sm text-white/50 m-0">Always write as &ldquo;LOGO.AI&rdquo; — capital L, lowercase logo, period, lowercase ai.</p>
              <div className="flex flex-wrap gap-3 pt-1">
                {[
                  { text: 'LOGO.AI', ok: true },
                  { text: 'LogoAI', ok: false },
                  { text: 'logoai', ok: false },
                  { text: 'Logo AI', ok: false },
                  { text: 'LOGO.AI', ok: false },
                ].map((item) => (
                  <span
                    key={item.text}
                    className="font-bricolage font-medium text-sm px-3 py-1.5 rounded-lg"
                    style={{
                      background: item.ok ? 'rgba(51,106,234,0.1)' : 'rgba(255,255,255,0.04)',
                      border: `1px solid ${item.ok ? 'rgba(51,106,234,0.3)' : 'rgba(255,255,255,0.08)'}`,
                      color: item.ok ? '#fff' : 'rgba(255,255,255,0.35)',
                    }}
                  >
                    {item.ok ? '✓ ' : '✕ '}{item.text}
                  </span>
                ))}
              </div>
            </div>

            <div className="w-full grid grid-cols-1 md:grid-cols-2 gap-5 text-left">
              <div className="rounded-2xl p-7 flex flex-col gap-4" style={{ border: '1px solid rgba(84,87,94,0.3)' }}>
                <p className="font-bricolage text-xs font-medium text-white/40 uppercase tracking-[2px] m-0">Do</p>
                <ul className="flex flex-col gap-2.5 m-0 pl-0 list-none">
                  {GUIDELINES_DO.map((item) => (
                    <li key={item} className="flex items-start gap-2.5">
                      <span className="mt-[3px] text-white/40 flex-shrink-0">
                        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><polyline points="20 6 9 17 4 12"/></svg>
                      </span>
                      <span className="font-bricolage text-sm leading-[1.6em] text-white/55">{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
              <div className="rounded-2xl p-7 flex flex-col gap-4" style={{ border: '1px solid rgba(84,87,94,0.3)' }}>
                <p className="font-bricolage text-xs font-medium text-white/40 uppercase tracking-[2px] m-0">Don&apos;t</p>
                <ul className="flex flex-col gap-2.5 m-0 pl-0 list-none">
                  {GUIDELINES_DONT.map((item) => (
                    <li key={item} className="flex items-start gap-2.5">
                      <span className="mt-[3px] text-white/30 flex-shrink-0">
                        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
                      </span>
                      <span className="font-bricolage text-sm leading-[1.6em] text-white/55">{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
      </PageSection>

      {/* ── Media Contact ── */}
      <PageSection>
        <div className="max-w-[95%] sm:max-w-[90%] mx-auto flex flex-col items-center text-center gap-6">
            <div className="flex flex-col items-center gap-2 max-w-[700px]">
              <h2 className="font-bricolage font-medium text-[24px] md:text-[36px] leading-[1.2em] tracking-[-0.03em] m-0">
                Let&apos;s talk
              </h2>
              <p className="font-bricolage text-base text-white/50 m-0 max-w-[480px]">
                For interview requests, embargoed materials, early product access, or custom brand assets — our media team is here to help. Response within 24 hours.
              </p>
            </div>
            <a
              href="mailto:press@logo.ai"
              className="inline-flex items-center gap-2 font-bricolage font-semibold text-white no-underline transition-all duration-200 flex-shrink-0 hover:opacity-90"
              style={{ background: BLUE, borderRadius: 12, padding: 'clamp(14px,2vw,20px) clamp(20px,3vw,32px)', fontSize: 'clamp(18px,1.8vw,20px)' }}
            >
              press@logo.ai
            </a>
          </div>
      </PageSection>
    </PageWrapper>
  )
}
